### PR TITLE
Constants refactor with open loop sim drive fix

### LINKED ISSUE #37: TASK - Convert constants files to interfaces
**Description**
Currently the constants files are abstract classes with default values. These defaults are only used in test cases. The rework proposes to convert the constants files to interfaces, moving the default implementation to the test namespace. Other implementations will be done in dependent projects.

### PR DESCRIPTION
**Pull request by shueja**
Signed-off-by: shueja-personal <j.a.shue@outlook.com>
Closes #37 
Also includes the constants changes needed to properly drive the robot in open loop sim. For future reference, drivePercentages() called the Talon set() directly (the one with control mode), which bypasses the Speedcontroller things that drive sim pulls from.

### CODE REVIEW

File: src/main/java/frc/lib/wrappers/motorcontrollers/NomadTalonSRX.java [hunk 1]
```diff
@@ -22,7 +32,9 @@
     protected boolean manualFollowing = false;
     protected double lastLeaderOutput = Double.NaN;
     protected double currentLeaderOutput = Double.NaN;
-
+    /**
```
Comment (JoeyFabel) [inline src/main/java/frc/lib/wrappers/motorcontrollers/NomadTalonSRX.java:35]: Everything looks good and I think is ready to merge. 
What is this comment about (The first javadoc one, about a NomadEncoder)? I tried to paste the full thing below, but it doesn't want to format right. This just seemed like an extra comment to me.
 /**
     * A quadrature NomadEncoder connected to the Talon.
     */
    /**
     * Constructs a TalonSRX, reverts it to factory default, and sets brake mode.
     * 
     * @param port The CAN ID of this Talon
     */
    public NomadTalonSRX(int port) {
        super(port);
        configFactoryDefault();
        setNeutralMode(NeutralMode.Brake);
        setSafetyEnabled(false);
    }

**Review by JoeyFabel — APPROVED** [review]

File: src/main/java/frc/lib/wrappers/motorcontrollers/NomadTalonSRX.java (hunk 1 above)
Comment (shueja) [reply src/main/java/frc/lib/wrappers/motorcontrollers/NomadTalonSRX.java:35]: Fixed. I do have several other stuff I left as comments because it's a "recommended implementation" (things like creating drive kinematics using the track width), and I wanted to keep it with the parent class's file. That one was a stray from an experiment I did.

Comment (shueja) [reply src/main/java/frc/lib/wrappers/motorcontrollers/NomadTalonSRX.java:35]: > I tried to paste the full thing below, but it doesn't want to format righ

You can use triple backticks ``` to format as code btw.
